name       : python-keras-preprocessing
version    : 1.1.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/6d/2b/d45a295e6b31d8b6663b705dff2f178ae16e8d2eac41097810a411d7b10f/Keras_Preprocessing-1.1.0.tar.gz : 5a8debe01d840de93d49e05ccf1c9b81ae30e210d34dacbcc47aeb3049b528e5
homepage   : https://keras.io
license    : MIT
component  : programming.python
summary    : Utilities for working with image data, text data, and sequence data
description: |
    Keras Preprocessing is the data preprocessing and data augmentation module of the Keras deep learning library. It provides utilities for working with image data, text data, and sequence data.
rundeps    :
    - python-six
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
