name       : python-keras-preprocessing
version    : 1.1.2
release    : 6
source     :
    - https://pypi.io/packages/source/K/Keras-Preprocessing/Keras_Preprocessing-1.1.2.tar.gz : add82567c50c8bc648c14195bf544a5ce7c1f76761536956c3d2978970179ef3
homepage   : https://keras.io
license    : MIT
component  : programming.python
summary    : Utilities for working with image data, text data, and sequence data
description: |
    Keras Preprocessing is the data preprocessing and data augmentation module of the Keras deep learning library. It provides utilities for working with image data, text data, and sequence data.
rundeps    :
    - python-six
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
